### ISSUE TITLE
time cost during evaluation

### ISSUE THREAD

**Issue by Watson52** [dotchen/LAV#8]
Hi, Chen.
When I evaluate the method, it cost a lot of time. It took over 1 hour to finish the route_0 in routes_lav_valid.xml file while the time ratio was under 0.2. In addition, when I collecting data via Carla challange(LBC), I found the FPS is about 4 FPS that also quite time-consuming. And I found the CPU or memory of GPU are still have many available resources.

1. I want to ask the could I accelerate the process during evaluate or data collecting? Like by setting the FPS. Or the ratio only depend on my device performance.
2. To collect large dataset like LAV provided, did you start multiple processes to collect data simultaneously? How long did it took for collecting the provided dataset?

btw, I just use one TITAN Xp for above try. Looking forward to your reply.

**Comment by dotchen** [comment]
1. You can change the rendering quality to `Low` to make it faster at the cost of fidelity. I don't recommend this since the online leaderboard uses the default `Epic` rendering mode. You can also change the trafficmanager to non physics mode, but again not recommended for the same reason above.
2. Yes, I parallelize 8 with actors. Similar codes for parallel data collection are provided in the [World on Rails](https://github.com/dotchen/WorldOnRails) repo.  Time duration varies depending on your hardware but mine took about 4 days.

Let me know if you have more questions.

**Comment by Watson52** [comment]
> 1. You can change the rendering quality to `Low` to make it faster at the cost of fidelity. I don't recommend this since the online leaderboard uses the default `Epic` rendering mode. You can also change the trafficmanager to non physics mode, but again not recommended for the same reason above.
> 2. Yes, I parallelize 8 with actors. Similar codes for parallel data collection are provided in the [World on Rails](https://github.com/dotchen/WorldOnRails) repo.  Time duration varies depending on your hardware but mine took about 4 days.
> 
> Let me know if you have more questions.

Thanks for your suggestions! I have try the `Low` quality model but it will occurs distortion like rgb images get wrong. And I will learn the WOR carefully for parallel processing.
